### ISSUE TITLE
No payment error message in frontend

### ISSUE THREAD

**Issue by nicogroen** [ICEPAY/Magento#17]
Our Magento version = 1.9.3.4
Icepay advanced module = 1.2.11

After a failed payment, the customer will be redirected to our Shopping Cart page (the order is not officially closed). The shopping cart page is not showing the error message. We can only find the error message in the Magento backend and Icepay portal. How can we solve this issue?

**Comment by tsygankov** [comment]
Hi  nicogroen,

You can try to enable logging:

![image](https://user-images.githubusercontent.com/15112699/32705980-557bcc2a-c822-11e7-9fda-c2a5e26662b6.png)

I will provide more details tomorrow.

**Comment by nicogroen** [comment]
OK. Can you please provide more details?

**Comment by tsygankov** [comment]
Hi nicogroen,

Sorry for the late answer, probably I misunderstood the problem. If I understand you correctly the error is known and can be found in the Magento backend and ICEPAY portal, just for some reason customers are not notified the payment has failed?

Can you please copy-paste the error message?

As you can [see](https://github.com/ICEPAY/Magento/blob/303b9c5cb1efb497f80df4b53b4f6d7561642bd0/app/code/community/Icepay/IceCore/Model/Icepay/Result.php#L63-L78) the module should show the error message if ICEPAY replied with the predefined error code (starting from 'ERR'). If customers are redirected to the Shopping Cart page most likely [this](https://github.com/ICEPAY/Magento/blob/303b9c5cb1efb497f80df4b53b4f6d7561642bd0/app/code/community/Icepay/IceCore/Model/Icepay/Result.php#L65-L71) code block is executed and error message is saved to 'checkout/session'. Later the error message should be rendered by Magento core, but something goes wrong. It is possible that the error massage is rendered on another page (as in [this](https://magento.stackexchange.com/a/16639) example) or removed by 3rd party modules. Please check if your UI theme supports error message rendering.

Please also check if the Error URL setting is correct. It should look like this:

![image](https://user-images.githubusercontent.com/15112699/32867311-137b3ab8-ca75-11e7-8bec-4686c62c2168.png)

**Comment by nicogroen** [comment]
Hello Tsygankov, 
Yes, you describe the problem correctly.
When we use our result URL we receive: "ICEPAY result page installed correctly". So this shouldn't be the problem. 

I forgot to share we run a multi-store environment with two domains. The problem occurs only on our second domain. I will share you our domain's in a private message.

Do you think we have to update to another module version (see my first post)?

Kind regards,
Nico

**Comment by tsygankov** [comment]
Yes, please try to update to v1.2.13. I see that there is no release package available on GitHub, but you can get the source code from the master branch. I will ask my colleagues to add the release package.

I'm not sure if the change that we introduced in v1.2.13 will solve the problem, I need to know at least your domain names to check this.

1.2.13 | 08/05/2017 | Store-specific Success and Error URLs
-- | -- | --

If you have multi-store environment with two domains (different URLs), then in v1.2.11 Success and Error URLs are handled incorrectly and users are always redirected to the default store.

> Preconditions:
> Multi-store environment with two domains:
> - Store 1: default store, www.mydomain.nl
> - Store 2: www.mydomain2.nl
> Same Merchant ID is used for both stores
> 
> Steps to reproduce:
> 1) Create an order in Store 2 (www.mydomain2.nl)
> 2) Start the payment process using credit card (user will be redirected to the ICEPAY payment\checkout page)
> 3) On the ICEPAY payment\checkout page cancel the payment (user will be redirected back to the webshop)
> 
> Expected result:
> User is redirected to Store 2
> 
> Observed: 
> User is always redirected to the default store.
> 

In v1.2.13 you can enable store-specific Success\Error URLs so that ICEPAY will ignore the settings in [portal](https://portal.icepay.com/) and use the URLs provided by the module. So if you see that customers are redirected to the wrong store you definitely need to enable the "Store-specific URLs" feature in the module configuration.

**Comment by nicogroen** [comment]
Thank you. Problem is solved with new module version.
