### ISSUE TITLE
ICEPAY SOAP service keeps connections and processess open killing our servers

### ISSUE THREAD

**Issue by inikolovski** [ICEPAY/Magento#4]
Whenever there are delays or issues on the ICEPAY service on the side of ICEPAY the magento module keeps checkout and postback processess/transactions open on the PHP Magento side.

This results in an increase of processess which keep connections open and keep stacking up killing databases and web nodes...

**Comment by RicardoJ** [comment]
Thank you for submitting this issue.

I cannot reproduce this issue, unfortunately. We can however adjust the [following file](https://github.com/icepay/Magento/blob/master/app/code/community/Icepay/IceCore/Model/Webservice/Core.php#L37) by replacing this part:

```php
$this->client = new SoapClient($this->serviceURL, array(
    'encoding'   => 'UTF-8',
    'cache_wsdl' => 'WSDL_CACHE_NONE'
));
```

by this part:

```php
$this->client = new SoapClient($this->serviceURL, array(
    'encoding'           => 'UTF-8',
    'cache_wsdl'         => 'WSDL_CACHE_NONE',
    'connection_timeout' => 90
));
```

The connection_timeout option defines a timeout in seconds for the connection to the SOAP service. This option does not define a timeout for services with slow responses. To limit the time to wait for calls to finish the default_socket_timeout setting is available:

`ini_set('default_socket_timeout', 90);`

If my theory is correct, the call will be dropped due to the timeout and therefore will return with a error in the transaction. The `default_socket_timeout` will make sure to close a open socket if there is no reasonable reponse within 90 seconds.

I'd like to hear your thoughts.

**Comment by inikolovski** [comment]
Thanks for the suggestion. Unfortunately we had tried this already before; With a connection_timeout of 5 seconds:

Igor N (author) - September 22, 2015 10:28, commit: 283a6034e3

```php
$this->client = new SoapClient($this->serviceURL, array('cache_wsdl' => 'WSDL_CACHE_NONE', 'encoding' => 'UTF-8', "connection_timeout" => 5)); 
```
Didn't help.

We are in the process of upgrading PHP. The current version we have has a bug in default socket timeout when using SSL streams:
https://bugs.php.net/bug.php?id=48524
https://bugs.php.net/bug.php?id=41631

In my opinion we could save on a lot of connections by caching the WSDL. 

Would that work with your Service? Or is there a need to retrieve a fresh WSDL every time a SoapClient is instanciated?

During an outage or slowdown at your end; when you try to retrieve the WSDL in a browser. It takes at least 30 seconds to get it. Letting the client cache it would be a good idea if this is possible.

It would also save you guys some resources by treating the WSDL as static content and serving it through a caching proxy.

**Comment by RicardoJ** [comment]
Thank you for your information. I see no problem whatsoever to caching the WSDL.

It is not necessary to obtain the WSDL on every request, however, I strongly suggest that you create a cronjob to get the WSDL once a week even though our WSDL does not change mutch.

**Comment by inikolovski** [comment]
Thanks for the information.

Maybe it would be a good idea to make this configurable from the magento admin?

Icepay core system setting like Use WSDL cache or something like that comes to mind.
